version: "2"

services:
  rabbit:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/definitions.json:/opt/definitions.json:ro
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro

  postgres:
      restart: always
      image: "sameersbn/postgresql:9.6-2"
      ports:
        - "5432:5432"
      environment:
        - DEBUG=false

        - DB_USER=admin
        - DB_PASS=hunter2
        - DB_NAME=backend
      volumes:
        - /srv/docker/postgresql:/var/lib/postgresql
